apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: storages.platform.example.com
spec:
  group: platform.example.com
  names:
    kind: Storage
    plural: storages
  claimNames:
    kind: StorageClaim
    plural: storageclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              cloud:
                type: string
                enum: [aws, gcp]
                description: Cloud provider
              size:
                type: string
                enum: [small, medium, large]
                description: Storage size
            required:
            - cloud
            - size
