apiVersion: v1
kind: Service
metadata:
  name: security-assessment
  namespace: security-assessment
spec:
  selector:
    app: security-assessment
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
