apiVersion: v1
kind: Namespace
metadata:
  name: gpu-operator
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  chart: gpu-operator
  repo: https://helm.ngc.nvidia.com/nvidia
  targetNamespace: gpu-operator
  set:
    operator.defaultRuntime: containerd
    toolkit.enabled: true
    devicePlugin.enabled: true
    dcgmExporter.enabled: true
    gfd.enabled: true
    migManager.enabled: true
    nodeStatusExporter.enabled: true
    validator.plugin.env[0].name: WITH_WORKLOAD
    validator.plugin.env[0].value: "true"
