apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-app-secret
  namespace: default
spec:
  encryptedData:
    password: AgBX3mXYZ... # This would be the actual encrypted data
  template:
    metadata:
      name: my-app-secret
    type: Opaque
