global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['order:8001']
  
  - job_name: 'payment-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['payment:8002']
  
  - job_name: 'inventory-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['inventory:8003']
  
  - job_name: 'notification-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['notification:8004']
